services:
  nginx:
    build:
      context: ./nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - ./nginx/entrypoint.sh:/entrypoint.sh:ro
      - ./nginx/www:/var/www/html
      - ./nginx/cronfile:/etc/cron.d/certbot-renew
      - ./nginx/certbot:/etc/letsencrypt
      - ./nginx/certbot-webroot:/var/www/certbot
      - /etc/letsencrypt/live/lm.flexyz.work:/etc/letsencrypt/live/lm.flexyz.work:ro
      - /etc/letsencrypt/archive/lm.flexyz.work:/etc/letsencrypt/archive/lm.flexyz.work:ro
      - /etc/letsencrypt/renewal:/etc/letsencrypt/renewal:ro
    networks:
      - app-network
    depends_on:
      - backend-${ACTIVE}
      - frontend-${ACTIVE}
    environment:
      - ACTIVE=${ACTIVE}
      - DOMAIN=lm.flexyz.work
      - EMAIL=flexyzwork@gmail.com
    env_file:
      - .env
    entrypoint: ['/bin/sh', '/entrypoint.sh']

  backend-green:
    image: kix.ocir.io/axunckhvyv1v/lm-backend:green
    restart: always
    ports:
      - '8003:8001'
    env_file:
      - ./server/.env
    volumes:
      - backend_data:/app/data
    networks:
      - app-network

  backend-blue:
    image: kix.ocir.io/axunckhvyv1v/lm-backend:blue
    restart: always
    ports:
      - '8002:8001'
    env_file:
      - ./server/.env
    volumes:
      - backend_data:/app/data
    networks:
      - app-network

  frontend-green:
    image: kix.ocir.io/axunckhvyv1v/lm-frontend:green
    restart: always
    ports:
      - '3003:3000'
    env_file:
      - ./client/.env
    volumes:
      - frontend_data:/app/data
    networks:
      - app-network

  frontend-blue:
    image: kix.ocir.io/axunckhvyv1v/lm-frontend:blue
    restart: always
    ports:
      - '3002:3000'
    env_file:
      - ./client/.env
    volumes:
      - frontend_data:/app/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  backend_data:
  frontend_data:
